name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.9, 3.14.3]
        # https://xrootd.web.cern.ch/repo/stable/el10/x86_64/
        xrootd-version: [5.7.2, 5.8.4, 5.9.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Docker image
        run: docker build -t xrootd --build-arg xrootd_version=$XROOTD_VERSION --build-arg python_version=$PYTHON_VERSION --progress=plain .
        env:
          XROOTD_VERSION: ${{ matrix.xrootd-version }}
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Run tests
        run: docker run -h xrootdpyfs -t xrootd
